import type { Metadata } from "next";
import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${jetbrainsMono.variable} antialiased bg-zinc-800 text-purple-500`}
      >
        <div className="mx-auto p-4 sm:max-w-xl md:max-w-3xl lg:max-w-5xl xl:max-w-7xl ">
          <Navbar />
          {children}
          <Footer />
          <h1 className="text-base text-center p-4">
            &copy; {new Date().getFullYear()} CS Expo. All rights reserved.
          </h1>
        </div>
      </body>
    </html>
  );
}
